### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by drgrigg** [jkinross/wilkie-collins_the-moonstone#2]
I’m currently working on “Bleak House” by Dickens, should be finished in a couple of weeks, after which I’ll be looking for my next project.

I’ve noticed that there hasn’t been any activity on this project for a while. I’ve completed a couple of books by Wilkie Collins myself, he’s my favourite Victorian-era writer. Do you need any help with completing this one?

**Comment by jkinross** [comment]
Its mostly done. It just needs proofed.
If you would like to proof it to complete it, feel free.

**Comment by drgrigg** [comment]
Sure, more than happy to do that. It’s several years at least since I last read it.  But I can’t start until I’ve finished proofing Bleak House, which will take me a couple of weeks, perhaps. 

Are you happy for me to fork your repository and submit any changes I spot during proofreading as pull requests?

**Comment by jkinross** [comment]
That works for me.

**Comment by drgrigg** [comment]
Jeffrey: I've finished proof-reading and making various fixes of things I found along the way.

I discovered that the Gutenberg transcription seems to be based on the Chatto and Windus British edition rather than the Comedie Humaine American edition you link to, so I've added the former to the sources of scans in content.opf, colophon and imprint. Would you like me to write the long-description for content.opf? I've already added my short-description.

Are you OK with me adding myself in as a secondary producer of the book? I note by the way that there wasn't a personal link for yourself in content.opf etc., so I've just added in a link to your github profile so that the book would build and pass Lint checks, but obviously this might not be what you want. Could you advise?

There are still a couple of Lint errors being reported about the ToC but I can't figure out why! I might need to ask Alex.

**Comment by jkinross** [comment]
Feel free to write the long description, adding yourself as a producer, and leaving a link to my github profile.

Thanks for the help.

**Comment by drgrigg** [comment]
Jeffrey: I think I've completed work now on the book. Please feel free to build it yourself and have a look. When building, I use this terminal command to put the dist folder outside of Git:

` ~/tools/build . --output-dir="../dist" --kindle --kobo --check`

Unless you have any objections, I'll ask Alex to do his review and hopefully it can be released soon. Thanks for letting me contribute, it's been fun!
