### ISSUE TITLE
<h2> headings should be <h3> in "narrative" subchapters

### ISSUE THREAD

**Issue by acabal** [jkinross/wilkie-collins_the-moonstone#4]
In the "Narrative" subchapters, the titles should be `<h3>` instead of `<h2>`, because `<h2>` is the level of the narrative headers.

**Comment by acabal** [comment]
Same in the Epilogue. The Prologue seems correct.

**Comment by drgrigg** [comment]
Dang! Of course you are correct. Should have spotted that myself.
