### ISSUE TITLE
Stray <i> without semantic

### ISSUE THREAD

**Issue by acabal** [jkinross/wilkie-collins_the-moonstone#6]
One instance of Robinson Crusoe does not have semantics, you can just do a global search for "`<i>`". Note that the trailing "s" should not be in the italics, since it is not part of the book title.

**Comment by drgrigg** [comment]
I think I left it un-semanticated because it was a plural. But I'll fix as you suggest.

**Comment by drgrigg** [comment]
There are no other floating <i> tags.
